### ISSUE TITLE
Cant run npm run load

### ISSUE THREAD

**Issue by tomscholz** [fabiomaciel/simple-mtg#48]
[scholzto@shaula simple-mtg]$ npm run load

> simple-mtg@0.0.1 load /var/www/virtual/scholzto/simple-mtg
> node ./src/loadSets.js

/var/www/virtual/scholzto/html/simple-mtg/node_modules/mongoose/node_modules/mongodb/lib/server.js:261
        process.nextTick(function() { throw err; })
                                      ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at null.<anonymous> (/var/www/virtual/scholzto/html/simple-mtg/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/var/www/virtual/scholzto/html/simple-mtg/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/var/www/virtual/scholzto/html/simple-mtg/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

npm ERR! Linux 2.6.32-573.12.1.el6.x86_64
npm ERR! argv "/package/host/localhost/nodejs-4.5.0/bin/node" "/package/host/localhost/nodejs-4/bin/npm" "run" "load"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! simple-mtg@0.0.1 load: `node ./src/loadSets.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the simple-mtg@0.0.1 load script 'node ./src/loadSets.js'.
npm ERR! This is most likely a problem with the simple-mtg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./src/loadSets.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs simple-mtg
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls simple-mtg
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/virtual/scholzto/html/simple-mtg/npm-debug.log
[scholzto@shaula simple-mtg]$

**Comment by andarilhoz** [comment]
@tomscholz Hi, that could be your mongo settings, try the folowings:
- See if mongodb is installed and running
- Check for mongodb host address (the default on this project is localhost at 27017)
- try again

please let me know if anything else goes wrong (:

**Comment by tomscholz** [comment]
@andarilhoz Which node version are you using? And yes :) MongoDb is installed

**Comment by andarilhoz** [comment]
@tomscholz  6.4.0, hmm strange thing

**Comment by fabiomaciel** [comment]
node v4.2.3 is fully functional

**Comment by fabiomaciel** [comment]
@tomscholz i tried to run without mongodb running and that the exactly error that shows in my bash

**Comment by tomscholz** [comment]
@andarilhoz @fabiomaciel Ok. I don't want to say this :), but you both were right. MongoDB wasn't installed. Now it works just fine 💃
